### PR TITLE
Fix `-` flag for `moonc`

### LINKED ISSUE #431: "Read from stdin" broken in moonc
According to the output of `moonc -h`, supplying the option `-` (and no other option) is supposed to read from stdin and output to stdout, but this doesn't seem to work:

```
$ moonc -
-       Can't find file  
```

Supplying the `/dev/stdin` works to circumvent it at least on Linux, but it makes for very wordy commands like:

```
$ cat <<EOF | moonc -p /dev/stdin
print 'Hello, World!'
EOF
return print('Hello, World!')  
```

### PR DESCRIPTION
**Pull request by natnat-mc**
`moonc` currently tells argparse to expect `-`, but actually checks for `--` on the cli, which breaks `moonc -`; this PR fixes this and forces `-` to be the only argument (like `-h` tells us) (fixes #431)

### CODE REVIEW

**Comment by natnat-mc** [comment]
(this is for #431)

**Comment by qaisjp** [comment]
If you put the term "Fixes #1431" in your main pull request comment, GitHub will automatically link the PR with that issue and auto-close the issue if this PR is merged.

**Comment by natnat-mc** [comment]
> If you put the term "Fixes #431" in your main pull request comment, GitHub will automatically link the PR with that issue and auto-close the issue if this PR is merged.

huh i thought it only worked in commit messages, done

**Comment by leafo** [comment]
Thanks

**Pull request merged**
