### PR TITLE
Add support for a new list table creation syntax.

### PR DESCRIPTION
**Pull request by fendrin**
```MoonScript
{
  id: first_value
  foo: bar
  id: second_value
}
```

id used to be bound to second_value.
This patch will create a list, meaning it is syntactic sugar for:
```MoonScript
{
  id: { first_value, second_value }
  foo: bar
}
```

### CODE REVIEW

**Comment by leafo** [comment]
hmm, in all the times that I've included a key twice in a table literal it's been a bug. I've actually wanted to make moonscript throw an error when it encounters it. Thoughts?

**Comment by kirbyfan64** [comment]
I've never done this intentionally, only by accident.

**Comment by fendrin** [comment]
Please allow me to present my use case and give some reasoning for the feature.
When used as static content description language, MoonScript does much better than Lua syntax wise.

Only the list syntax is still quite parentheses heavy and spoils the day.
Although the new syntax allows for grouping matching items together which are in different items but related in some other context.

I hope the example gives some insight in my thoughts.

```MoonScript
scenario
    id: "01_Defend_the_Forest"
    name: [[Defend the Forest]]

    map: "test_map"
    turns: 24
    next_scenario: "02_Assassins"

    time: DEFAULT_SCHEDULE
    playlist: {"knolls", "wanderer", "sad"}

    Prestart: ->
        part AOI_BIGMAP
            music: "elvish-theme"
            story: [[The arrival of humans and orcs caused turmoil among the nations of the Great Continent. Elves, previously in uneasy balance with dwarves and others, had for centuries fought nothing more than an occasional skirmish. They were to find themselves facing conflicts of a long-forgotten intensity.]]

        part AOI_BIGMAP
            story: [[Their first encounter with the newcomers went less well than either side might have wished.]]

        part AOI_BIGMAP
            story: [[But humans, though crude and brash, at least had in them a creative spark which elves could recognize as akin to their own nature. Orcs seemed completely alien.]]
        part aoi_bigmap

        part AOI_BIGMAP
            story: [[For some years after Haldric’s people landed, orcs remained scarce more than a rumor to trouble the green fastnesses of the elves. That remained so until the day that an elvish noble of ancient line, Erlornas by name, faced an enemy unlike any he had ever met before.]]

        part AOI_BIGMAP
            --po: "northern marches" is *not* a typo for "northern marshes" here.
            --po: In archaic English, "march" means "border country".
            story: [[The orcs were first sighted from the north marches of the great forest of Wesmere.]]

        AOI_TRACK(JOURNEY_01_NEW)

        STARTING_VILLAGES(1, 6)
        SCATTER_IMAGE("terrain=Re", 1, "scenery/rubble.png")

    side:
        side: 1
        controller: "human"
        recruit: "Elvish Archer, Elvish Fighter, Elvish Scout, Elvish Shaman"
        gold: QUANTITY 200, 150, 100
        income: 0
        team_id: "good"
        team_name: [[Elves]]
        --FLAG_VARIANT(wood-elvish)
        unit: CHARACTER_STATS_ERLORNAS { facing: "nw" }
        unit: NAMED_LOYAL_UNIT 1, "Elvish Rider",
            15, 18,
            "Lomarfel", [[Lomarfel]]
        --- @TODO find a way to attack them
        --           {
        --               facing: "ne"
        --               profile: "portraits/lomarfel.png"
        --           {

    side:
        side: 2
        controller: "ai"
        recruit: "Orcish Archer, Orcish Grunt, Wolf Rider"
        gold: QUANTITY 100, 125, 150
        income: 0
        team_id: "Orcs"
        team_name: [[Orcs]]
        --{FLAG_VARIANT6 ragged}
        unit:
            type: "Orcish Warrior"
            id: "Urugha"
            name: [[Urugha]]
            can_recruit: true
            facing: "se"
        ai:
            grouping: "offensive"
            attack_depth: 5

    Prestart: ->
        obj =
            objective:
                description: [[Defeat Urugha]]
                condition: "win"
            objective:
                description: [[Death of Erlornas]]
                condition: "lose"
            objective: TURNS_RUN_OUT
            gold_carryover:
                bonus: true
                carryover_percentage: 40
        if EASY
            tablex.join(obj, HINT([[Elves can move quickly and safely among the trees. Pick off the enemy grunts with your archers from the safety of the forest.]]))
        objective obj

    Start: ->
        message
            speaker: "Lomarfel"
            message: [[My lord! A party of aliens has made camp to the north and lays waste to the forest. Our scouts believe it’s a band of orcs.]]
        message
            speaker: "Erlornas"
            message: [[Orcs? It seems unlikely. The human king, Haldric, crushed them when they landed on these shores, and since then they’ve been no more than a bogey mothers use to scare the children.]]
        message
            speaker: "Lomarfel"
            message: [[So it seemed, my lord. Yet there is a band of them in the north cutting down healthy trees by the dozen, and making great fires from the wood. They trample the greensward into mud and do not even bury their foul dung. I believe I can smell the stench even here.]]
        message
            speaker: "Erlornas"
            message: [[So the grim tales of them prove true. They must not be allowed to continue; we must banish this blight from our forests. I shall marshal the wardens and drive them off. And the Council needs to hear of this; take the message and return with reinforcements, there might be more of them.]]
        message
            speaker: "Lomarfel"
            message: [[Yes, my lord!]]

        kill
            id: "Lomarfel"
        move_unit_fake
            type: "Elvish Rider"
            x: "15,14,14,13,12,11,10"
            y: "18,18,19,20,20,20,20"

        -- this is an example of a nested event
        event
            name: "Turn2"
            command: ->
                message
                    speaker: "Erlornas"
                    message: [[Look at them. Big, slow, clumsy and hardly a bow in hand. Keep to the trees, use your arrows and the day will be ours.]]

    TimeOver: ->
        message
            race: "elf"
            message: [[It’s hopeless; we’ve tried everything, and they’re still coming back.]]
        message
            speaker: "Urugha"
            message: [[Forward, you worthless worms! Look at them, they’re tired and afraid! You killed their will to fight, now go and finish the job!]]
        message
            speaker: "Erlornas"
            message: [[That cloud of dust on the horizon... flee! There’s more of the abominations heading this way! Fall back before we’re outnumbered and crushed.]]
        message
            speaker: "narrator"
            image: "wesnoth-icon"
            message: [[Lord Erlornas didn’t drive the orcs back, although he and his warriors tried their absolute best. When another war band arrived, elvish resistance crumbled.]]
        message
            speaker: "narrator"
            image: "wesnoth-icon"
            message: [[Of the ensuing events little is known, since much was lost in the chaos and confusion, but one thing is painfully sure. Elves lost the campaign.]]

    LastBreath:
        filter:
            id: "Erlornas"
        command: ->
            message
                speaker: "Erlornas"
                message: [[Ugh...]]
            message
                speaker: "Urugha"
                message: [[Finally! Got him!]]
            message
                race: "elf"
                not:
                    id: "Erlornas"
                message: [[Lord!]]
            message
                speaker: "Erlornas"
                message: [[Take... command... Drive them... away.]]
            message
                speaker: "narrator"
                image: "wesnoth-icon"
                message: [[Lord Erlornas died the day he first fought the orcs and never saw the end of the war. Given its final outcome, this was perhaps for the best.]]

    LastBreath:
        filter:
            id: "Urugha"
        command: ->
            message
                speaker: "unit"
                message: [[I’ve been bested, but the combat wasn’t fair... A thousand curses on you, withered coward! May you suffer... and when my master, Rualsha, finds you may he wipe your people from the face of this earth!]]

    Die:
        filter:
            id: "Urugha"
        command: ->
            message
                speaker: "Erlornas"
                message: [[Rualsha? Hmm... What if... Assemble a war-party, we need to scout north!]]
            endlevel
                result: "victory"
                bonus: true
                carryover_add: true
                carryover_percentage: 40

**Comment by branefreez** [comment]
I, also, have only done this by accident. Perhaps using a new syntax for this type of usage should be added:
```moonscript
tbl:
    foo: 'a'
    baz: 'element'
    +foo: 'bar'
```
such that it is equivalent to the following:
```moonscript
tbl:
    foo:
        'a'
        'bar'
    baz: 'element'
```
I suggest using the following syntax because we are **adding** to the values represented by the name  *index*:
```moonscript 
+index: value
```

**Comment by cbeck88** [comment]
For what it's worth, :+1: to @branefreez 's suggestion above

**Comment by Kingdaro** [comment]
I don't think it seems all that necessary. As @leafo and others have said before, I've only done this on accident, and it's always been a bug. Is it really that terrible to just write it normally?

In Lua, defining the same value twice in the table will resolve to the last definition and overwrite the others, so having different behavior than what one would expect in MoonScript seems a little more than dangerous. I'd think this assertion would be obvious...

**Comment by fendrin** [comment]
The example I presented above uses the mechanism from http://www.lua.org/pil/12.html to store the content of a game.

This means you typically have a file containing a handler function call (or maybe several) followed by a single huge table as the only argument.

MoonScript's table construction syntax is already very cool for that purpose.

Kingdaro wrote: Is it really that terrible to just write it normally?
Yes. :-)
A config file storing a scripted scenario like in the example can easily get a size above 2000 lines.
It can also easily contain definitions for more than 20 "issues".
I call an "issue" a thing in the scenario that concerns several different keys of a table.

The scenario coder should write all of an issues key entries consecutive or he has either jump around in the file madly or switch the issue context rapidly.
Both is braking the workflow.

Also, the result is much better readable if sub-table entries concerning the same issue can be grouped together.

**Comment by Kingdaro** [comment]
I'll reiterate that one or two edge cases should _never_ justify a rather ambiguous change in arguably one of Lua's most important paradigms. If you're concerned about readability, a change to the language itself shouldn't be your solution. Messy code is the fault of the writer, not the language.

**Comment by leafo** [comment]
After thinking about it more, I'm still not a fan of this syntax. I think people would invoke this more often as an accident than intentionally using the feature.

If you're looking to create a DSL to describe scenarios where you control how things are appended to a table, then maybe this guide will be helpful: http://leafo.net/guides/dsl-in-lua.html

This idea was used in Lapis for the configuration syntax: http://leafo.net/lapis/reference/moon_creating_configurations.html#configuration-example

**Comment by fendrin** [comment]
So far most comments said:
"I only used a key twice in a table constructor by accident."

An error that is caused by a wrong value in a table (old behavior) is harder to spot than the values being in a different data structure.
So I suspect the proposed syntax to improve the situation regarding accidents.

The link to the DSL guide is interesting.
But I do not want to go for a DSL.

My goal is not to cover some border cases but to improve the language's abilities regarding static configuration data storage.

I am fine with shipping my modified MoonScript version with the game.
Having the feature in MoonScript itself is not that important for me.

I just thought it would be somehow unfriendly to not offer my efforts in case they would have been found useful.

**Pull request closed without merging**
