### PR TITLE
make it use lua as default, not lua5.1

### PR DESCRIPTION
**Pull request by Nymphium**
default Makefile have us to use Lua5.1, but newest Lua is 5.3. I think we should'nt use Lua5.1.

### CODE REVIEW

**Comment by deathbeam** [comment]
And what about backwards compatiility? A lot of people still want to use LuaJIT.

**Comment by Nymphium** [comment]
Oh sorry I completely forgot which version LuaJIT is based on. How about like thhis: `LUA_VERSION=5.1 make ...` or normally `make ...`

**Comment by kirbyfan64** [comment]
Just put something like:

```make
LUA=lua
```

in the makefile and change the commands to use the variable. That way, when someone wants to use a different Lua binary, they can run:

```
make LUA=luajit ...
```

**Comment by Nymphium** [comment]
sounds better than mine :+1:

**Comment by leafo** [comment]
hmm, I use the makefile for my own personal workflow, and didn't indent other people to be using it. Maybe we can move the command out to a variable but still keep the default of 5.1?

**Comment by Nymphium** [comment]
I see. lua5.1 as default is reasonable, but I think the Makefile's variable to change Lua's version is userful for developers.

**Comment by tgoyne** [comment]
If you put `LUA=lua5.1` in the Makefile, then it will default to that if it is not overridden on the command line.

**Comment by leafo** [comment]
thanks, merged now

**Comment by Nymphium** [comment]
👏

**Pull request merged**
