### PR TITLE
Fixes #264

### LINKED ISSUE #264: Code coverage error
Running simple test from http://moonscript.org/reference/command_line.html#command-line-tools/moon/code-coverage:

1. Created a file `test.moon`
```moonscript
-- test.moon
first = ->
  print "hello"

second = ->
  print "world"

first!
```

2. Running `moon -c test.moon`

3. Error:
```
starting coverage
hello
/usr/bin/lua: .../myuser/.luarocks/share/lua/5.3/moonscript/cmd/coverage.lua:45: @test.moon: No such file or directory
stack traceback:
	[C]: in function 'assert'
	.../myuser/.luarocks/share/lua/5.3/moonscript/cmd/coverage.lua:45: in upvalue 'format_file'
	.../myuser/.luarocks/share/lua/5.3/moonscript/cmd/coverage.lua:119: in function <.../myuser/.luarocks/share/lua/5.3/moonscript/cmd/coverage.lua:86>
	(...tail calls...)
	[C]: in ?
```

When I create file `@test.moon`, I get this output:
```
starting coverage
hello
------| @@test.moon
     1| 
```
File `@test.moon` is empty.

**EDIT**: From what I understand seems like the coverage tool tries to open "@test.moon" file, which is not there. Probably removing this first "@" will fix the issue.

---
`lua -v`: `Lua 5.3.2  Copyright (C) 1994-2015 Lua.org, PUC-Rio`
`moon -v`: `MoonScript version 0.4.0`

### PR DESCRIPTION
**Pull request by pavel**
This is a fix for the issue #264.

### CODE REVIEW

**Comment by pavel** [comment]
Seems like Travis failed there with:
```
/moonscript/cmd/args.lua:5: attempt to call a nil value (global 'unpack')
```

Which I tend to think has nothing to do with changes in this pull request.

**Comment by ChickenNuggers** [comment]
You need to do: `local unpack = unpack or table.unpack`.

Lua 5.2 deprecated the global `unpack()` function for `table.unpack()`. Both work the same but are in different locations.

**Comment by pavel** [comment]
@ChickenNuggers thanks, that did the trick. Though it is very interesting as I have ran `busted`with no errors on my computer, and I have `Lua 5.3.2`.

**Comment by ChickenNuggers** [comment]
Lua sometimes is compiled with compatibility handlers (see my alt-getopt "solution"). Because of this, your version of Lua might have both `unpack` and `table.unpack`, or just `unpack`.

**Comment by ChickenNuggers** [comment]
@leafo master is failing with ^ btw

**Comment by ChickenNuggers** [comment]
@pavel check #269

**Pull request closed without merging**
